[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_escrow = "Eo9M2qhnJuRkZZsqGKhY9bxue7kSzowu5ppzgo5c2GWC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test_ts = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test = "cargo test-sbf"
